[versions]
jdk = "21"
sdk-compile = "36"
sdk-min = "23"
sdk-target = "36"

agp = "9.0.0"
android-chart = "3.1.0"
androidx-sqliteBundled = "2.6.2"
androidx-test-ext-junit = "1.3.0"
app-update = "2.1.0"
coil = "3.3.0"
compose-multiplatform = "1.10.0"
compose-multiplatform-material3 = "1.9.0"
compose-multiplatform-material-icons = "1.7.3"
compose-plugin = "1.10.0"
compose-test = "1.10.1"
coroutines = "1.10.2"
crashlytics = "3.0.6"
detekt = "1.23.8"
espresso-core = "3.7.0"
firebase-bom = "34.8.0"
google-services = "4.4.4"
koin-bom = "4.1.1"
kotlin = "2.2.21"
kotlinx-datetime="0.7.1"
kotlinx-serialization="1.9.0"
ksp = "2.3.3"
ktlint = "1.8.0"
ktor="3.3.3"
leak-canary = "2.14"
lottie = "6.7.1"
material = "1.13.0"
mockk = "1.14.7"
navigation = "2.9.1"
okhttp3 = "5.3.2"
robolectric = "4.16.1"
room = "2.8.4"
security = "1.1.0"
spotless-version = "8.2.0"
turbine = "1.2.1"
work-manager = "2.11.0"

[libraries]

#Android
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

#Android chart
android-chart = { group = "com.github.PhilJay", name = "MPAndroidChart", version.ref = "android-chart" }

#App update
app-update-ktx = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "app-update" }

#Compose Multiplatform
cmp-components-resources = { group = "org.jetbrains.compose.components", name = "components-resources", version.ref = "compose-multiplatform" }
cmp-material-icons-extended = { group = "org.jetbrains.compose.material", name = "material-icons-extended", version.ref = "compose-multiplatform-material-icons" }
cmp-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "compose-multiplatform-material3" }
cmp-ui-tooling = { group = "org.jetbrains.compose.ui", name = "ui-tooling", version.ref = "compose-multiplatform" }
cmp-ui-tooling-preview = { group = "org.jetbrains.compose.ui", name = "ui-tooling-preview", version.ref = "compose-multiplatform" }

#Coil
coil = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network-ktor3 = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }

#Coroutines
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

#Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-config = { module = "com.google.firebase:firebase-config" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }

#Koin
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
koin-work-manager = { module = "io.insert-koin:koin-androidx-workmanager" }

#Kotlin
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

#Ktor
ktor-client-contentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-client-serialization-kolinxJson = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

#Leak Canary
leak-canary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leak-canary" }

#Lottie
lottie = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }

#Navigation
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation" }

#Okhttp
okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3" }

#Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-sqlite-bundled = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "androidx-sqliteBundled" }

#Security
security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "security" }

#Work manager
work-manager = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work-manager" }

#Tests
kotlinx-test-core = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

#Android tests
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
compose-test-junit = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose-test" }
compose-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose-test" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
androidx-room = { id = "androidx.room", version.ref = "room" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-jetbrains = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless-version" }

[bundles]
compose-multiplatform = [
    "cmp-components-resources",
    "cmp-material-icons-extended",
    "cmp-material3",
    "cmp-ui-tooling-preview",
]
firebase = [
    "firebase-analytics",
    "firebase-auth",
    "firebase-config",
    "firebase-crashlytics",
    "firebase-firestore",
]
koin = [
    "koin-core",
    "koin-compose",
    "koin-compose-viewmodel",
]
ktor = [
    "ktor-client-contentNegotiation",
    "ktor-client-core",
    "ktor-client-serialization-kolinxJson",
]