[versions]
jdk = "17"
sdk-compile = "36"
sdk-min = "23"
sdk-target = "36"

agp = "8.12.1"
android-chart = "3.1.0"
androidx-hilt = "1.2.0"
androidx-test-ext-junit = "1.3.0"
app-update = "2.1.0"
coil = "2.7.0"
compose-activity = "1.10.1"
compose-bom = "2025.08.00"
compose-test = "1.9.0"
core-ktx = "1.17.0"
coroutines = "1.10.2"
crashlytics = "2.9.8"
detekt = "1.23.8"
espresso-core = "3.7.0"
firebase-bom = "34.1.0"
google-services = "4.4.3"
hilt = "2.57"
junit = "4.13.2"
kotlin = "2.2.10"
kotlinx-serialization="1.9.0"
ksp = "2.2.10-2.0.2"
ktlint = "1.5.0"
leak-canary = "2.14"
lifecycle = "2.9.2"
lottie = "6.6.7"
material = "1.12.0"
material3 = "1.3.2"
moshi = "1.15.2"
navigation = "2.9.3"
okhttp3 = "5.1.0"
retrofit = "3.0.0"
room = "2.7.2"
room-rxjava3-bridge = "3.0.2"
rxandroid = "3.0.2"
rxjava = "3.1.11"
rxkotlin = "3.0.1"
security = "1.1.0"
spotless-version = "7.2.1"
work-manager = "2.10.3"

[libraries]

#Android
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material3 = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3" }

#Android chart
android-chart = { group = "com.github.PhilJay", name = "MPAndroidChart", version.ref = "android-chart" }

#App update
app-update-ktx = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "app-update" }

#Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-material = { module = "androidx.compose.material:material" }
compose-material-icons = { module = "androidx.compose.material:material-icons-core" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
compose-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

#Coil
coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

#Coroutines
coroutines_rx = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx3", version.ref = "coroutines" }

#Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-config = { module = "com.google.firebase:firebase-config" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }

#Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidx-hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidx-hilt" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "androidx-hilt" }

#Kotlin
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

#Leak Canary
leak-canary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leak-canary" }

#Lottie
lottie = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }

#Moshi
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }

#Navigation
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

#Retrofit
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-adapter-rxjava = { group = "com.squareup.retrofit2", name = "adapter-rxjava3", version.ref = "retrofit" }
okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3" }
retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }

#Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-rxjava = { group = "androidx.room", name = "room-rxjava2", version.ref = "room" }
room-rxjava3-bridge = { group = "com.github.akarnokd", name = "rxjava3-bridge", version.ref = "room-rxjava3-bridge" }

#Rx
rxjava = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rxjava" }
rxkotlin = { group = "io.reactivex.rxjava3", name = "rxkotlin", version.ref = "rxkotlin" }
rxandroid = { group = "io.reactivex.rxjava3", name = "rxandroid", version.ref = "rxandroid" }

#Security
security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "security" }

#Work manager
work-manager = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work-manager" }

#Tests
junit = { group = "junit", name = "junit", version.ref = "junit" }

#Android tests
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
compose-test-junit = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose-test" }
compose-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose-test" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless-version" }

[bundles]
compose = [
    "compose-activity",
    "compose-graphics",
    "compose-material",
    "compose-material-icons",
    "compose-material-icons-extended",
    "compose-preview",
    "compose-runtime",
    "compose-tooling",
    "compose-ui",
]
firebase = [
    "firebase-analytics",
    "firebase-auth",
    "firebase-config",
    "firebase-crashlytics",
    "firebase-firestore",
]
retrofit = [
    "okhttp3-logging-interceptor",
    "retrofit",
    "retrofit-adapter-rxjava",
    "retrofit-converter-moshi",
]
rx = [
    "rxandroid",
    "rxjava",
    "rxkotlin",
]